require('plugins')
require('keymaps')
require('colorscheme')
require('options')
require('plugins.nvim-tree')
require('plugins.lualine')
require('plugins.lspconfig')
require('plugins.null-ls')
require('plugins.mason')
require('plugins.nvim-cmp')
require('plugins.toggleterm')
require('plugins.treesitter')

